# Generated by Django 5.1.7 on 2025-06-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='specialty',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.AddField(
            model_name='doctor',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certificates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_license',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
